name: "Setup environment"

runs:
  using: "composite"
  steps:
    - name: Use Python 3.9.17
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.17
    - name: Install Requirements
      run: pip3 install install -r requirements.txt
      shell: bash
    - name: Install ganache
      run: yarn global add ganache@7.9.1
      shell: bash
    - name: Compile contracts
      run: brownie compile
      shell: bash
