compiler:
  evm_version: london
  solc:
    version: "0.8.17"
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@balancer-labs/v2-solidity-utils=balancer-labs/balancer-v2-monorepo@tob-audit-phantom-stable/pkg/solidity-utils"
      - "@balancer-labs/v2-pool-utils=balancer-labs/balancer-v2-monorepo@tob-audit-phantom-stable/pkg/pool-utils"
      - "@balancer-labs/v2-asset-manager-utils=balancer-labs/balancer-v2-monorepo@tob-audit-phantom-stable/pkg/asset-manager-utils"
      - "@balancer-labs/v2-pool-weighted=balancer-labs/balancer-v2-monorepo@tob-audit-phantom-stable/pkg/pool-weighted"
      - "@balancer-labs/v2-vault=balancer-labs/balancer-v2-monorepo@tob-audit-phantom-stable/pkg/vault"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2"
      - "@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2/contracts"
      - "@usingtellor=tellor-io/usingtellor@5.0.4"

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.2
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.3.2
  - balancer-labs/balancer-v2-monorepo@tob-audit-phantom-stable
  - tellor-io/usingtellor@5.0.4

networks:
  development:
    cmd_settings:
      evm_version: london
    priority_fee: 2
  mainnet-fork:
    cmd_settings:
      evm_version: london
    priority_fee: 2
  polygon-fork:
    cmd_settings:
      evm_version: london
      unlock:
        - 0x8780779CAF2bC6D402DA5c3EC79A5007bB2edD90
    priority_fee: 2
