compiler:
  evm_version: null
  solc:
    version: "0.8.10"
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@balancer-labs/v2-solidity-utils=balancer-labs/balancer-v2-monorepo@tob-audit-phantom-stable/pkg/solidity-utils"
      - "@balancer-labs/v2-pool-utils=balancer-labs/balancer-v2-monorepo@tob-audit-phantom-stable/pkg/pool-utils"
      - "@balancer-labs/v2-asset-manager-utils=balancer-labs/balancer-v2-monorepo@tob-audit-phantom-stable/pkg/asset-manager-utils"
      - "@balancer-labs/v2-pool-weighted=balancer-labs/balancer-v2-monorepo@tob-audit-phantom-stable/pkg/pool-weighted"
      - "@balancer-labs/v2-vault=balancer-labs/balancer-v2-monorepo@tob-audit-phantom-stable/pkg/vault"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2"

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.3.2
  - balancer-labs/balancer-v2-monorepo@tob-audit-phantom-stable
