project_structure:
  build: build
  contracts: contracts
  interfaces: interfaces
  reports: reports
  scripts: scripts
  tests: tests

networks:
  default: development
  development:
    gas_limit: max
    gas_buffer: 1
    gas_price: 0
    reverting_tx_gas_limit: max
    default_contract_owner: true
    cmd_settings: null
  live:
    gas_limit: auto
    gas_buffer: 1.1
    gas_price: auto
    reverting_tx_gas_limit: false
    default_contract_owner: false

compiler:
  evm_version: null
  solc:
    version: null
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@balancer-labs/v2-solidity-utils=balancer-labs/balancer-v2-monorepo@tob-audit-phantom-stable/pkg/solidity-utils"
      - "@balancer-labs/v2-pool-utils=balancer-labs/balancer-v2-monorepo@tob-audit-phantom-stable/pkg/pool-utils"
      - "@balancer-labs/v2-asset-manager-utils=balancer-labs/balancer-v2-monorepo@tob-audit-phantom-stable/pkg/asset-manager-utils"
      - "@balancer-labs/v2-pool-weighted=balancer-labs/balancer-v2-monorepo@tob-audit-phantom-stable/pkg/pool-weighted"
      - "@balancer-labs/v2-vault=balancer-labs/balancer-v2-monorepo@tob-audit-phantom-stable/pkg/vault"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2"
  vyper:
    version: null

console:
  show_colors: true
  color_style: monokai
  auto_suggest: true
  completions: true
  editing_mode: emacs

reports:
  exclude_paths: null
  exclude_contracts: null
  only_include_project: true

hypothesis:
  deadline: null
  max_examples: 50
  report_multiple_bugs: False
  stateful_step_count: 10
  phases:
    explicit: true
    reuse: true
    generate: true
    target: true
    shrink: true

autofetch_sources: false
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.1.0
  - balancer-labs/balancer-v2-monorepo@tob-audit-phantom-stable
dev_deployment_artifacts: false
