name: Solidity CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn
      - name: Lint Contracts
        run: yarn run lint

  unit_test:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Run Unit Tests
        run: brownie test --coverage -m 'not mainnetFork' --failfast --hypothesis-seed 42

  integration_test:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      WEB3_INFURA_PROJECT_ID: ${{ secrets.WEB3_INFURA_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Run Integration Tests
        run: brownie test -m mainnetFork --network mainnet-fork --failfast --hypothesis-seed 42
